### ISSUE TITLE
Too many dependencies in nuget package

### ISSUE THREAD

**Issue by codingawayy** [UNOPS/atag#1]
When installing nuget package [ATag.EntityFrameworkCore](https://www.nuget.org/packages/atag.entityframeworkcore), a large number of other (possibly unneeded) packages is installed. I believe that it is caused by having a dependency on `Microsoft.EntityFrameworkCore.SqlServer.Design`. @mohammed-fuad can you please check if we can reduce the number of dependencies.

**Comment by mohammed-fuad** [comment]
Thanks @niaher for feedback. Will commit soon.

**Comment by mohammed-fuad** [comment]
new package version 0.0.6-beta is published
